- name: Install python 2 ( for 16.04 only )
  become: true
  raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- name: Install Base Environment
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - build-essential
    - emacs-nox

- name: Create deploy user group(s)
  group:
    name: "{{ item }}"
    state: present
  with_items: "{{ USER_GROUPS }}"

- name: Create deploy user
  user:
    append: yes
    groups: "sudo,{{ (USER_GROUPS | join(',')) }}"
    name: "{{ USER_NAME }}"
    password: "{{ lookup('password', 'credentials/deployer_passwd length=18') | password_hash('sha512') }}"
    shell: "{{ USER_SHELL }}"
    state: present
    update_password: on_create

- name: Setup authorized_keys
  authorized_key:
    key: "{{ item }}"
    user: "{{ USER_NAME }}"
    state: present
  with_file: "{{ PUBLIC_KEYS }}"